# Generated by Django 2.1.3 on 2018-11-19 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.CharField(max_length=10)),
                ('week_start', models.DateField()),
                ('tuesday', models.DateField()),
                ('thursday', models.DateField()),
                ('description', models.CharField(max_length=100)),
            ],
        ),
    ]
